remote_theme: just-the-docs/just-the-docs
title: "Two Tutorials for Mojo using Pocket Flow"
baseurl: "/pf-understand" # the subpath of your site, e.g. /blog
url: "https://MrBesterTester.github.io" # Done! Replace with your GitHub username

# Enable search
search_enabled: true

# Configure collections for your different guides
collections:
  crawl4ai:
    permalink: "/:collection/:path/"
    output: true
  modular_max:
    permalink: "/:collection/:path/"
    output: true
  mojo-v1:
    permalink: "/:collection/:path/"
    output: true
  mojo-v2:
    permalink: "/:collection/:path/"
    output: true

# Configure the navigation hierarchy
just_the_docs:
  collections:
    crawl4ai:
      name: Crawl4AI
    modular_max:
      name: Modular Max
    mojo-v1:
      name: Mojo (v1)
    mojo-v2:
      name: Mojo (v2)
